services:
  - type: web
    name: youtube-jukebox
    runtime: node
    plan: free
    buildCommand: npm install && npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
